POST http://localhost:3030/auth/register
Content-Type: application/json

{
    "name": "Roberto",
    "email": "abca@email.com",
    "password": "senha123",
    "role": "user"
}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 272
etag: W/"110-xddveb8Tsc4b2Q0fpZLZBl7/h1A"
date: Fri, 11 Jul 2025 19:56:27 GMT
connection: close
###
POST http://localhost:3030/auth/login
Content-Type: application/json

{
    "email": "abca@email.com",
    "password": "senha123"
}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 318
etag: W/"13e-mUopAgIGgVDcmA9n4ZrcerAPTJ0"
date: Fri, 11 Jul 2025 20:01:00 GMT
connection: close
###
GET http://localhost:3030/users?order=asc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2ZGZlNTEzLWNmNTctNGJkNS1iZmI3LTg0MGFlZjA1NDNlYyIsIm5hbWUiOiJKb2hhbm4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTIyNjMyMDksImV4cCI6MTc1MjM0OTYwOX0.DJCJyuOSPgr8jzAlU19m6Zu7Gv_1tN6HhE-PnX1tqAs

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 522
etag: W/"20a-s9iPdOF+MFvh8+HxyYF2S1Q5Mao"
date: Fri, 11 Jul 2025 19:58:09 GMT
connection: close
###
GET http://localhost:3030/users/56dfe513-cf57-4bd5-bfb7-840aef0543ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2ZGZlNTEzLWNmNTctNGJkNS1iZmI3LTg0MGFlZjA1NDNlYyIsIm5hbWUiOiJKb2hhbm4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTIyNjMyMDksImV4cCI6MTc1MjM0OTYwOX0.DJCJyuOSPgr8jzAlU19m6Zu7Gv_1tN6HhE-PnX1tqAs

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 310
etag: W/"136-UZzXrK/RHYc7wNK1oObk++ga2BE"
date: Fri, 11 Jul 2025 19:47:39 GMT
connection: close
###
GET http://localhost:3030/users/inactive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2ZGZlNTEzLWNmNTctNGJkNS1iZmI3LTg0MGFlZjA1NDNlYyIsIm5hbWUiOiJKb2hhbm4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTIyNjMyMDksImV4cCI6MTc1MjM0OTYwOX0.DJCJyuOSPgr8jzAlU19m6Zu7Gv_1tN6HhE-PnX1tqAs

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 90
etag: W/"5a-gTNUL9PP7H5I2b4XU8UIXv59d84"
date: Fri, 11 Jul 2025 19:47:59 GMT
connection: close
###
PUT http://localhost:3030/users/5fdc3ddc-11a0-47d9-8bbb-586763c319e5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZGMzZGRjLTExYTAtNDdkOS04YmJiLTU4Njc2M2MzMTllNSIsIm5hbWUiOiJSb2JlcnRvIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTIyNjMzMzQsImV4cCI6MTc1MjM0OTczNH0.cHTFqaoa_A7asFmy2RdTiEsrIjJglN3_Uc-UP7mWI00

{
    "role": "user"
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 95
etag: W/"5f-nvPMQ0Y+3jtqsuQzSW4Ck3xpg64"
date: Fri, 11 Jul 2025 19:49:57 GMT
connection: close
###
DELETE http://localhost:3030/users/5fdc3ddc-11a0-47d9-8bbb-586763c319e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2ZGZlNTEzLWNmNTctNGJkNS1iZmI3LTg0MGFlZjA1NDNlYyIsIm5hbWUiOiJKb2hhbm4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTIyNjMyMDksImV4cCI6MTc1MjM0OTYwOX0.DJCJyuOSPgr8jzAlU19m6Zu7Gv_1tN6HhE-PnX1tqAs

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 295
etag: W/"127-Peh+EjBZV+LqZscWh/iVBYTs/7c"
date: Fri, 11 Jul 2025 19:51:16 GMT
connection: close