POST http://localhost:3030/auth/register
Content-Type: application/json

{
    "name": "Leandro",
    "email": "wcxr@email.com",
    "password": "senha123",
    "role": "user"
}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 255
etag: W/"ff-fW5SjOy7npGCo+zwB1lpnu9HiMw"
date: Wed, 02 Jul 2025 18:57:56 GMT
connection: close
###
POST http://localhost:3030/auth/login
Content-Type: application/json

{
    "email": "abcd@email.com",
    "password": "senha123"
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 318
etag: W/"13e-hHEFYyGwfM3HNrkBgR1lcK3brgY"
date: Wed, 02 Jul 2025 19:27:16 GMT
connection: close
###
GET http://localhost:3030/users?order=asc&role=admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3ODg0ZWQ2LWU2ODUtNDk0Yi04YjlkLTY0YTZiNGU5YWJlNiIsIm5hbWUiOiJKb2hhbm4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTE0ODI2OTMsImV4cCI6MTc1MTU2OTA5M30.WNOvCmxcNg0JNPSFZMO-wdcBHc_NWH77XkgIFHMHIuk

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 264
etag: W/"108-xA9LISuturl9+laDQ4TnINjvJh8"
date: Wed, 02 Jul 2025 18:59:48 GMT
connection: close
###
GET http://localhost:3030/users/eeb19ff3-e675-4717-a232-2d38433408db
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwN2EzZWU2LTUwMDYtNGMyNy05ZTJkLThlMGE1ODQxMzQxOSIsIm5hbWUiOiJKb2hhbm4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTE0MDA4MTIsImV4cCI6MTc1MTQ4NzIxMn0.dQUwcu1NBrCjs3maejv5IYbo2W-PLIPyXxI3I9_SB74

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 88
etag: W/"58-fRBsM5Iaf6Xc/lSlVqIaL39xhzA"
date: Tue, 01 Jul 2025 20:02:04 GMT
connection: close
###
GET http://localhost:3030/users/inactive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3ODg0ZWQ2LWU2ODUtNDk0Yi04YjlkLTY0YTZiNGU5YWJlNiIsIm5hbWUiOiJKb2hhbm4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTE0ODM1NjQsImV4cCI6MTc1MTU2OTk2NH0.x4ug2yWQQ3ptPjzQX0gBbUJCM0weV_uUXvXI8ZoJDLw

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 681
etag: W/"2a9-FeSrGzGqSm+SoqxqnvNHFq9NKnU"
date: Wed, 02 Jul 2025 19:27:27 GMT
connection: close
###
PUT http://localhost:3030/users/eeb19ff3-e675-4717-a232-2d38433408db
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYjE5ZmYzLWU2NzUtNDcxNy1hMjMyLTJkMzg0MzM0MDhkYiIsIm5hbWUiOiJSb2JlcnRvIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDAxMDI0LCJleHAiOjE3NTE0ODc0MjR9.eKD7dw8s6h4vpylHYRSNCDls95adQs14Dp7UXX4ztf4

{
    "role": "user"
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 259
etag: W/"103-CZ2qXk0DFhHV8w1DI6339ZIFa2Y"
date: Tue, 01 Jul 2025 20:18:51 GMT
connection: close
###
DELETE http://localhost:3030/users/eeb19ff3-e675-4717-a232-2d38433408db
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlYjE5ZmYzLWU2NzUtNDcxNy1hMjMyLTJkMzg0MzM0MDhkYiIsIm5hbWUiOiJSb2JlcnRvIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTE0MDEyNDEsImV4cCI6MTc1MTQ4NzY0MX0.lJmYJJAt_uFi6b_ZvzZyxTEoRDXwtebFZ2BdYI242Nc

HTTP/1.1 403  - Forbidden
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 93
etag: W/"5d-Nepxjz5v62nLCKICtqiJeJdJNxE"
date: Tue, 01 Jul 2025 20:22:31 GMT
connection: close