POST http://localhost:3030/auth/register
Content-Type: application/json

{
    "name": "Johann",
    "email": "email@email.com",
    "password": "senha123",
    "role": "admin"
}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 74
etag: W/"4a-7CWsxdk5Sj/6h3oH9YLcDN/sp5Q"
date: Sun, 29 Jun 2025 01:45:12 GMT
connection: close
###
POST http://localhost:3030/auth/login
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "senha123"
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 318
etag: W/"13e-LXArLMFk0CHSCRZpC8Q1lS+/u6M"
date: Sun, 29 Jun 2025 01:40:51 GMT
connection: close
###
POST http://localhost:3030/debug
Content-Type: application/json

{
    "msg": "teste"
}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 34
etag: W/"22-v1E6vD46f34pJ5YYhplGJdWSMy8"
date: Sat, 28 Jun 2025 22:29:51 GMT
connection: close